name: downloaders
services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - LAN_NETWORK=192.168.1.0/16
      - WEBUI_PORT=8081
      - TORRENTING_PORT=${TORRENTING_PORT}
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_PATH}/qbittorrent-vpn/config:/config
      - ${DOCKER_PATH}/qbittorrent-vpn/downloads:/downloads
      - ${MEDIA_PATH}:/media
    network_mode: "service:gluetun"
    restart: unless-stopped

  slskd:
    image: slskd/slskd:latest
    container_name: slskd
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ}
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_UMASK=022
    volumes:
      - ${DOCKER_PATH}/slskd:/app
      - ${MEDIA_PATH}:/media
    network_mode: "service:gluetun"
    restart: unless-stopped

  # SABnzbd
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_PATH}/SABnzbd:/config
      - ${MEDIA_PATH}:/media
    ports:
      - 8080:8080
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    ports:
      - 8081:8081 # qBittorrent WebUI
      - ${TORRENTING_PORT}:${TORRENTING_PORT} # qBittorrent incoming TCP
      - ${TORRENTING_PORT}:${TORRENTING_PORT}/udp # qBittorrent incoming UDP
      - 8118:8118
      - 5030:5030 # slskd
      - 50300:50300 # slskd
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UPDATER_PERIOD=2h
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_DNS=${WIREGUARD_DNS}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - WIREGUARD_MTU=${WIREGUARD_MTU}
      - FIREWALL_VPN_INPUT_PORTS=${FIREWALL_VPN_INPUT_PORTS}
    networks:
      default:
        aliases:
          - vpn
          - qbt
          - slskd

    restart: unless-stopped

networks:
  default:
    external: true
    name: downloaders
