services:
  caddy:
    container_name: caddy
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "2019:2019" # Caddy admin port
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./site:/usr/share/caddy:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
