services:
  caddy:
    container_name: caddy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=${TZ:-UTC}
    ports:
      - "2019:2019" # Caddy admin port
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/usr/share/caddy
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
