services:
  caddy:
    container_name: caddy
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "2019:2019" # Caddy admin port
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./site:/usr/share/caddy:ro
      - ./data:/data
      - ./config:/config
    restart: unless-stopped
