name: portainer
services:
  portainer:
    image: portainer/portainer-ee:alpine
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_PATH}/portainer:/data
