name: infrastructure
services:
  # Watchtower - Automatic container updates
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - TZ=${TZ}
      - WATCHTOWER_SCHEDULE=0 0 3 * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
